### ISSUE TITLE
Сan't create @IBOutlet

### ISSUE THREAD

**Issue by JAGUAR108** [ChiliLabs/CHIOTPField#2]
after dragging from the storyboard, xcode gives an error
`@IBOutlet property cannot have non-'@objc' class type 'CHIOTPFieldTwo'`

**Comment by chili-ios** [comment]
Hey @JAGUAR108 ,

In your class, it should be UITextField and that should solve the problem.

**Comment by JAGUAR108** [comment]
Then how can I access the properties of the CHIOTPFieldTwo class?

**Comment by chili-ios** [comment]
You can set up everything in the storyboard
![image](https://user-images.githubusercontent.com/19732707/95734451-245d9680-0c8c-11eb-94e7-f41ab70c5308.png)

Or, another option is to make a computed property in your class that will cast UItextfield to CHIOTPField

**Comment by JAGUAR108** [comment]
I want to change borderColor when the entry code is wrong, the cast doesn't work:
`Could not cast value of type 'UITextField' (0x1fab1bc78) to 'Polys.CHIOTPFieldTwo' (0x102fc1630).`

**Comment by JAGUAR108** [comment]
It helped, thanks! final code:
`var textField: CHIOTPFieldTwo? {
	return codeTextField as? CHIOTPFieldTwo
}`
